import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../models/models.dart';
import 'format.dart';

/// Renders a shift report (X snapshot or Z close-of-day) as a real
/// PDF document and hands it to the system share sheet, so managers
/// can send it to the bookkeeper over WhatsApp or e-mail.
Future<void> shareReportPdf(ShiftReport report) async {
  final pw.Document doc = pw.Document();
  final String kind = report.isZ ? 'Z report' : 'X report';

  final List<List<String>> rows = <List<String>>[
    <String>['Register', report.register],
    <String>['Cashier', report.cashier],
    <String>['Transactions', '${report.transactions}'],
    <String>['Items sold', '${report.itemsSold}'],
    <String>['Gross sales', money(report.grossSales)],
    <String>['Discounts', money(report.discounts)],
    <String>['Net sales', money(report.netSales)],
    <String>['Cash', money(report.cash)],
    <String>['Card', money(report.card)],
    <String>['Mobile', money(report.mobile)],
    <String>['Opening float', money(report.openingFloat)],
    <String>['Expected drawer', money(report.expectedDrawer)],
    if (report.isZ) ...<List<String>>[
      <String>['Counted cash', money(report.countedCash)],
      <String>['Variance', money(report.variance)],
      if (report.note.isNotEmpty) <String>['Note', report.note],
    ],
    <String>['Average order', money(report.avgOrder)],
  ];

  doc.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.fromLTRB(36, 42, 36, 42),
      build: (pw.Context context) => <pw.Widget>[
        pw.Padding(
          padding: const pw.EdgeInsets.only(bottom: 16),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: <pw.Widget>[
              pw.Text('Sami POS',
                  style: pw.TextStyle(
                      fontSize: 22, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 2),
              pw.Text(
                  '$kind · ${report.id} · ${shortDate(report.time)}',
                  style: const pw.TextStyle(fontSize: 12)),
            ],
          ),
        ),
        pw.TableHelper.fromTextArray(
          headers: <String>['Line', 'Amount'],
          data: rows,
          oddRowDecoration:
              const pw.BoxDecoration(color: PdfColor.fromInt(0xFFF7F3EE)),
          headerStyle:
              pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10),
          cellStyle: const pw.TextStyle(fontSize: 10),
          cellAlignment: pw.Alignment.centerLeft,
          columnWidths: <int, pw.TableColumnWidth>{
            0: const pw.FlexColumnWidth(2),
            1: const pw.FlexColumnWidth(1.4),
          },
        ),
        pw.Padding(
          padding: const pw.EdgeInsets.only(top: 14),
          child: pw.Text(
            'Generated by Sami POS · ${clockLabel(report.time)}',
            style: const pw.TextStyle(fontSize: 9),
          ),
        ),
      ],
    ),
  );

  await Printing.sharePdf(
    bytes: await doc.save(),
    filename: 'SamiPOS-${report.id}.pdf',
  );
}
